### ISSUE TITLE
Create Pop-Up About

### ISSUE THREAD

**Issue by tuanle03** [tuanle03/Scratch_Cards#25]
Introduce how to play game

**Comment by yongieghe** [comment]
Each person will be dealt 6 cards. 
Players arrange their cards into two piles in order to maximize the sum of the remainders when dividing the sum of any three cards by 10. 
Then, compare the piles with the host according to the rule: max against max, min against min. 
If you win both comparisons, you receive coins. If it's a tie, you keep your coins. If you lose, you lose your betting money.
